// Vercel Edge Middleware (issues #757/#759): give the /compare/:a-vs-:b URL
// space real status codes.
//
// Problem: /compare/:a-vs-:b is a static rewrite to compare.html, so ANY pair
// — including /compare/totally-fake-gpu-vs-another-fake-one — returned HTTP
// 200 and client-side JS then wrote an SEO title/meta description for
// hardware that doesn't exist (soft-404, indexable junk pair space).
//
// Fix: this middleware validates both slugs against the build-time manifest
// public/compare-hardware-slugs.json (generated by
// scripts/generate-compare-slugs.mjs from /api/benchmarks?groupBy=hardware)
// and answers unknown pairs with a genuine HTTP 404 (noindex) before the
// rewrite runs. Known pairs fall through to compare.html unchanged.
//
// Fail-open: if the manifest can't be fetched (cold-start hiccup), the request
// proceeds to the SPA, which enforces the same rule client-side (noindex +
// "not found" UI in ComparePage.jsx). Better a soft-200 than a hard outage.
import { parseComparePath, comparePairStatus } from './src/utils/compareSlug.js';

const MANIFEST_PATH = '/compare-hardware-slugs.json';

/** Per-isinstance memo; edge instances are short-lived so no TTL is needed. */
let slugsPromise = null;

function loadSlugs(origin) {
  if (!slugsPromise) {
    slugsPromise = fetch(`${origin}${MANIFEST_PATH}`)
      .then(res => (res.ok ? res.json() : null))
      .then(manifest => (manifest && Array.isArray(manifest.slugs) ? new Set(manifest.slugs) : null))
      .catch(() => null);
  }
  return slugsPromise;
}

function notFoundResponse(a, b) {
  const body = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="robots" content="noindex">
<title>Comparison not found (404) | LLM Prefill &amp; Decode Visualizer</title>
</head>
<body style="font-family: system-ui, sans-serif; max-width: 640px; margin: 48px auto; padding: 0 20px;">
<h1>404 — comparison not found</h1>
<p>No measured benchmark runs for <code>${a}</code> or <code>${b}</code>, so this comparison does not exist.</p>
<p>Valid pairs are enumerated in <a href="/compare-hardware-slugs.json">/compare-hardware-slugs.json</a>;
each hardware group's slug is also exposed by <a href="/api/benchmarks?groupBy=hardware">/api/benchmarks?groupBy=hardware</a>.</p>
<p><a href="/">Open the LLM Prefill &amp; Decode Visualizer →</a></p>
</body>
</html>`;
  return new Response(body, {
    status: 404,
    headers: {
      'content-type': 'text/html; charset=utf-8',
      'x-robots-tag': 'noindex',
      'cache-control': 'public, max-age=3600',
    },
  });
}

export default async function middleware(request) {
  // Only judge page views; anything else falls through untouched.
  if (request.method !== 'GET' && request.method !== 'HEAD') return;

  const url = new URL(request.url);
  const parsed = parseComparePath(url.pathname);
  if (!parsed) return; // not a well-formed pair path — let the SPA handle it

  const slugs = await loadSlugs(url.origin);
  if (!slugs) return; // fail-open (see header comment)

  if (comparePairStatus(slugs, parsed.a, parsed.b) !== 'ok') {
    return notFoundResponse(parsed.a, parsed.b);
  }
  // Both slugs known: continue to compare.html.
  return;
}

export const config = {
  matcher: '/compare/:path*',
};

/** Test hook: drop the per-instance manifest memo. */
export function _resetManifestCache() {
  slugsPromise = null;
}
