// Export a simulation as a shareable step-by-step markdown walkthrough.
//
// Like exportPng.js, this has no external dependencies. The builders are pure
// functions (no DOM access) so the output is deterministic and unit-testable:
// the same inputs always produce byte-identical markdown, which is what makes
// the export safe to paste into slides, course notes, or homework evidence.

import { formatTime, formatTokens } from './presets.js';
import { calculateAgenticTimeline } from './agenticMath.js';

// ---------------------------------------------------------------------------
// Deep links
// ---------------------------------------------------------------------------

// Build a URL that reproduces the exact config when opened: keeps every
// current query param (preset, speeds, per-tab settings) and pins the tab,
// while dropping transient state like autoplay.
export function buildDeepLink(tab) {
  if (typeof window === 'undefined') return '';
  const p = new URLSearchParams(window.location.search);
  if (tab) p.set('tab', tab);
  p.delete('autoplay');
  const qs = p.toString();
  return `${window.location.origin}${window.location.pathname}${qs ? `?${qs}` : ''}`;
}

// ---------------------------------------------------------------------------
// Single-turn chat export
// ---------------------------------------------------------------------------

export function buildSingleTurnMarkdown({
  promptTokens,
  outputTokens,
  prefillSpeed,
  decodeSpeed,
  specEnabled,
  draftTokens,
  acceptance,
  effectiveDecodeSpeed,
  deepLink
}) {
  const safePrompt = Math.max(0, promptTokens || 0);
  const safeOutput = Math.max(0, outputTokens || 0);
  const ttft = safePrompt / prefillSpeed;
  const decodeTime = safeOutput / effectiveDecodeSpeed;
  const total = ttft + decodeTime;
  const tpotMs = effectiveDecodeSpeed > 0 ? 1000 / effectiveDecodeSpeed : Infinity;
  const throughput = total > 0 ? (safePrompt + safeOutput) / total : 0;
  const prefillPct = total > 0 ? (ttft / total) * 100 : 0;
  const decodePct = total > 0 ? (decodeTime / total) * 100 : 0;

  const specSection = specEnabled ? `
### Speculative decoding

\`\`\`
tokens/step = 1 + k·α = 1 + ${draftTokens}·${acceptance} = ${(1 + draftTokens * acceptance).toFixed(2)}
steps/s     = decode ÷ (1 + k·c_draft) = ${decodeSpeed} ÷ (1 + ${draftTokens}·0.2) = ${(decodeSpeed / (1 + draftTokens * 0.2)).toFixed(1)}
effective   = steps/s × tokens/step = ${Math.round(effectiveDecodeSpeed)} tok/s
\`\`\`

Draft model proposes k = ${draftTokens} tokens per step, target verifies in one pass; acceptance α = ${acceptance}, draft cost c_draft ≈ 0.2.
` : '';

  return `# Single-Turn Chat Simulation

Step-by-step walkthrough generated by the LLM Prefill & Decode Visualizer.

## Inputs

| Parameter | Value |
| --- | --- |
| Prompt length | ${safePrompt.toLocaleString()} tok |
| Target output length | ${safeOutput.toLocaleString()} tok |
| Prefill speed | ${prefillSpeed.toLocaleString()} tok/s |
| Decode speed (base) | ${decodeSpeed.toLocaleString()} tok/s |
| Speculative decoding | ${specEnabled ? `ON (k = ${draftTokens}, α = ${acceptance})` : 'OFF'} |
${specSection}
## Formulas

\`\`\`
TTFT   = prompt ÷ prefill        = ${safePrompt} ÷ ${prefillSpeed} = ${ttft.toFixed(4)}s (${formatTime(ttft)})
TPOT   = 1000 ÷ decode          = 1000 ÷ ${Math.round(effectiveDecodeSpeed * 100) / 100} = ${Number.isFinite(tpotMs) ? `${tpotMs.toFixed(1)} ms` : '∞'}
Decode = output ÷ decode        = ${safeOutput} ÷ ${Math.round(effectiveDecodeSpeed * 100) / 100} = ${decodeTime.toFixed(4)}s (${formatTime(decodeTime)})
Total  = TTFT + Decode          = ${ttft.toFixed(4)} + ${decodeTime.toFixed(4)} = ${total.toFixed(4)}s (${formatTime(total)})
\`\`\`

## Final metrics

| Metric | Value |
| --- | --- |
| TTFT (time to first token) | ${formatTime(ttft)} |
| TPOT (time per output token) | ${Number.isFinite(tpotMs) ? `${tpotMs.toFixed(1)} ms` : '∞'} |
| Total chat walltime | ${formatTime(total)} |
| Effective throughput | ${throughput.toFixed(1)} tok/s |
| Walltime split | Prefill ${prefillPct.toFixed(1)}% · Decode ${decodePct.toFixed(1)}% |

## Reproduce this run

Open this URL — it encodes the exact configuration above:

\`\`\`
${deepLink}
\`\`\`
`;
}

// ---------------------------------------------------------------------------
// Agentic tool-loop export
// ---------------------------------------------------------------------------

export function buildAgenticMarkdown({
  numTurns,
  basePromptTokens,
  toolOutputTokensPerTurn,
  decodeTokensPerTurn,
  enablePrefixCaching,
  prefillSpeed,
  decodeSpeed,
  deepLink
}) {
  const turns = calculateAgenticTimeline({
    numTurns,
    basePromptTokens,
    toolOutputTokensPerTurn,
    decodeTokensPerTurn,
    prefillSpeed,
    decodeSpeed,
    enablePrefixCaching
  });

  const totalWalltime = turns.reduce((acc, t) => acc + t.turnWalltime, 0);
  const noCacheWalltime = calculateAgenticTimeline({
    numTurns,
    basePromptTokens,
    toolOutputTokensPerTurn,
    decodeTokensPerTurn,
    prefillSpeed,
    decodeSpeed,
    enablePrefixCaching: false
  }).reduce((acc, t) => acc + t.turnWalltime, 0);
  const saved = noCacheWalltime - totalWalltime;
  const savedPct = noCacheWalltime > 0 ? (saved / noCacheWalltime) * 100 : 0;
  const finalContext = turns.length
    ? turns[turns.length - 1].totalPromptTokens + turns[turns.length - 1].decodeTokens
    : 0;
  const totalTokens = turns.reduce((acc, t) => acc + t.newTokensPrefilled + t.decodeTokens, 0);
  const throughput = totalWalltime > 0 ? totalTokens / totalWalltime : 0;

  const first = turns[0];
  const cachedTurn = turns.find(t => t.isCached);

  const waterfallRows = turns.map(t => [
    `T${t.turn}`,
    t.isCached ? 'cached ⚡' : 'full ingest',
    `${formatTokens(t.totalPromptTokens)}`,
    `${formatTokens(t.newTokensPrefilled)}`,
    formatTime(t.prefillTime),
    formatTime(t.decodeTime),
    formatTime(t.turnWalltime),
    formatTime(t.cumulativeWalltime)
  ]);
  const waterfallTable = [
    '| Turn | Prefill mode | History context | Prefilled tok | Prefill time | Decode time | Turn walltime | Cumulative |',
    '| --- | --- | --- | --- | --- | --- | --- | --- |',
    ...waterfallRows.map(r => `| ${r.join(' | ')} |`)
  ].join('\n');

  return `# Agentic Tool-Loop Simulation

Step-by-step walkthrough generated by the LLM Prefill & Decode Visualizer.

## Inputs

| Parameter | Value |
| --- | --- |
| Agent turns | ${numTurns} |
| Initial system prompt | ${basePromptTokens.toLocaleString()} tok |
| Tool result per turn | +${toolOutputTokensPerTurn.toLocaleString()} tok |
| Agent thought per turn | ${decodeTokensPerTurn.toLocaleString()} tok |
| Prefill speed | ${prefillSpeed.toLocaleString()} tok/s |
| Decode speed | ${decodeSpeed.toLocaleString()} tok/s |
| Prefix caching | ${enablePrefixCaching ? 'ON (KV reuse)' : 'OFF (full re-prefill)'} |

## Formulas

\`\`\`
prefill_time(T) = new_tokens_prefilled ÷ prefill_speed
decode_time(T)  = decode_tokens_per_turn ÷ decode_speed
turn_walltime   = prefill_time + decode_time
\`\`\`

Turn 1 substituted:

\`\`\`
prefill_time = ${first.newTokensPrefilled} ÷ ${prefillSpeed} = ${first.prefillTime.toFixed(4)}s (${formatTime(first.prefillTime)})
decode_time  = ${decodeTokensPerTurn} ÷ ${decodeSpeed} = ${first.decodeTime.toFixed(4)}s (${formatTime(first.decodeTime)})
turn 1 total = ${first.prefillTime.toFixed(4)} + ${first.decodeTime.toFixed(4)} = ${first.turnWalltime.toFixed(4)}s (${formatTime(first.turnWalltime)})
\`\`\`
${cachedTurn ? `
With prefix caching, turn ${cachedTurn.turn}+ only prefills the newly appended tool output (${toolOutputTokensPerTurn.toLocaleString()} tok) instead of the whole accumulated history:

\`\`\`
prefill_time(T${cachedTurn.turn}) = ${cachedTurn.newTokensPrefilled} ÷ ${prefillSpeed} = ${cachedTurn.prefillTime.toFixed(4)}s
\`\`\`
` : ''}
## Per-turn waterfall

${waterfallTable}

## Final metrics

| Metric | Value |
| --- | --- |
| Total walltime (${numTurns} turns) | ${formatTime(totalWalltime)} |
| Final context (KV cache) | ${finalContext.toLocaleString()} tok |
| Tokens processed (prefill + decode) | ${totalTokens.toLocaleString()} tok |
| Average throughput | ${throughput.toFixed(1)} tok/s |
| Without prefix caching | ${formatTime(noCacheWalltime)} |
| Caching savings | ${enablePrefixCaching ? `${formatTime(saved)} (${savedPct.toFixed(0)}%)` : '— (caching off)'} |

## Reproduce this run

Open this URL — it encodes the exact configuration above:

\`\`\`
${deepLink}
\`\`\`
`;
}

// ---------------------------------------------------------------------------
// Delivery: download as file + copy to clipboard
// ---------------------------------------------------------------------------

export function downloadMarkdown(markdown, filename = 'simulation.md') {
  const blob = new Blob([markdown], { type: 'text/markdown;charset=utf-8' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  a.remove();
  setTimeout(() => URL.revokeObjectURL(url), 5000);
}

export async function copyMarkdownToClipboard(markdown) {
  try {
    await navigator.clipboard.writeText(markdown);
    return true;
  } catch {
    // Clipboard API can be unavailable (http origins, permissions); fall back
    // to a hidden-textarea execCommand copy, then give up gracefully.
    try {
      const ta = document.createElement('textarea');
      ta.value = markdown;
      ta.style.position = 'fixed';
      ta.style.opacity = '0';
      document.body.appendChild(ta);
      ta.select();
      const ok = document.execCommand('copy');
      ta.remove();
      return ok;
    } catch {
      return false;
    }
  }
}
