/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run inference math (TTFT, TPOT, walltime, VRAM)
         * @description Pass ?model=<name> plus parameters. Omit model for a self-describing capability list. Also accepts POST with a JSON body, or a batch of up to 50 parameter sets via POST {"batch": [...]} / GET ?batch=[...] — returns per-index results with per-item ok/error status. Every computation response carries a deterministic `id` (calc_<hash> of the resolved inputs) that can be replayed via /api/calc/{id}.
         */
        get: {
            parameters: {
                query?: {
                    model?: "singleTurn" | "speculative" | "batched" | "agentic" | "kvCache" | "flagged" | "cost";
                    /** @description singleTurn/batched/agentic/cost */
                    promptTokens?: number;
                    /** @description singleTurn/batched/agentic/cost */
                    outputTokens?: number;
                    /** @description tok/s */
                    prefillSpeed?: number;
                    /** @description tok/s */
                    decodeSpeed?: number;
                    /** @description agentic */
                    numTurns?: number;
                    /** @description agentic */
                    enablePrefixCaching?: boolean;
                    /** @description batched/kvCache */
                    batchSize?: number;
                    /** @description speculative: draft tokens per step */
                    draftTokens?: number;
                    /** @description speculative: 0..1. Response includes breakevenAcceptanceRate — below it speculation is slower than vanilla decode. */
                    acceptanceRate?: number;
                    /** @description cost: purchase price, amortized over amortizationMonths (default 36) */
                    hardwarePriceUsd?: number;
                    /** @description cost: $/kWh, default 0.15 */
                    electricityRatePerKwh?: number;
                    /** @description cost: whole-rig wall power under load */
                    powerDrawWatts?: number;
                    /** @description cost: months to spread hardware price over, default 36 */
                    amortizationMonths?: number;
                    /** @description kvCache preset arch */
                    architecture?: "llama70b" | "llama8b" | "qwen72b" | "mistral7b";
                    /** @description kvCache */
                    contextLength?: number;
                    /** @description kvCache: FP16/FP8/INT4 */
                    precisionBytes?: 2 | 1 | 0.5;
                    /** @description flagged: comma-separated engine flag ids (flash-attn,kv-q8,kv-q4,no-mmap,vllm-fp8-kv,vllm-o3). Documented heuristic deltas; response carries a per-flag audit trail. */
                    flags?: string;
                    /** @description Validate + echo parsed params (defaults filled in) without executing any math. Returns { dry_run: true, model, inputs, id?, note }; the id matches the real call. Also applies per-item inside a batch via "dry_run": true in the POST body. */
                    dry_run?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Computed metrics object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "calc_9536a8f7358a",
                         *       "inputs": {
                         *         "promptTokens": 4096,
                         *         "outputTokens": 512,
                         *         "prefillSpeed": 3800,
                         *         "decodeSpeed": 105
                         *       },
                         *       "warnings": [],
                         *       "ttftSeconds": 1.077895,
                         *       "tpotMs": 9.52381,
                         *       "decodeSeconds": 4.87619,
                         *       "totalWalltimeSeconds": 5.954085,
                         *       "effectiveThroughputTokPerSec": 773.922414,
                         *       "prefillSharePct": 18.103448,
                         *       "decodeSharePct": 81.896552,
                         *       "schema_version": "1"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                /** @description Invalid parameters (code INVALID_PARAMS) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                /** @description Internal server error (code INTERNAL) */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/vram": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Combined model + KV-cache + context VRAM from just an hfId
         * @description Resolves layers, hidden dim, GQA heads, head dim and weight size from the Hugging Face config automatically — no architecture params needed. Answers "will this rig OOM at 64k?". Optional vramGb budget returns a fits flag plus the max context that fits; optional numTurns+tokensPerTurn projects per-turn KV growth with the exact overflow turn.
         */
        get: {
            parameters: {
                query: {
                    /** @description Hugging Face repo id or URL, e.g. meta-llama/Llama-3.1-8B-Instruct */
                    hfId: string;
                    /** @description context length in tokens */
                    context?: number;
                    /** @description quant tag (fp16, q8_0, q6_k, q5_k_m, q4_k_m, q4_0, q3_k_m, q2_k, fp8, …); unknown tags assume ~4.85 bpw and are flagged */
                    quant?: string;
                    batchSize?: number;
                    /** @description KV cache precision: 2=FP16, 1=FP8, 0.5=INT4 */
                    kvPrecisionBytes?: number;
                    /** @description optional VRAM budget → fits flag + maxContextTokens (upper bound) */
                    vramGb?: number;
                    /** @description with tokensPerTurn: project KV growth over N agentic turns */
                    numTurns?: number;
                    /** @description tokens added to context per turn */
                    tokensPerTurn?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Resolved model + weights/kv/total VRAM breakdown */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Missing hfId */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unknown hfId on huggingface.co */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description config.json lacks required architecture fields */
                422: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/calc/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Replay a computation or recommendation from its deterministic id
         * @description Ids are content hashes (calc_ + 12 hex chars of sha256 over the normalized request) returned as `id` by /api/compute and /api/best. They are not stored anywhere: re-send the original parameters alongside the id and this endpoint re-runs the same math and returns the result with verified:true. A mismatching parameter set is rejected with the expected id.
         */
        get: {
            parameters: {
                query?: {
                    endpoint?: "compute" | "best";
                    /** @description The same model + params (or best filters) that minted the id. Defaults may be omitted — they resolve identically before hashing. */
                    "<original request parameters>"?: string;
                };
                header?: never;
                path: {
                    id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Recomputed result, stamped verified:true and carrying the id */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Malformed id, missing replay parameters, or id/parameter mismatch (body.expected carries the correct id) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Built-in hardware speed presets and workload scenarios */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description {hardware[], scenarios[]}; each hardware entry carries power/thermal guidance (#69): tdpWatts (board power), loadWatts (typical whole-rig wattage under inference), psuWatts (recommended PSU size) and powerNote — null where not applicable (cloud/edge/custom). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "description": "Built-in hardware speed presets and workload scenario presets. Use these values as inputs to /api/compute.",
                         *       "hardware": [
                         *         {
                         *           "id": "rtx4090_exl2",
                         *           "name": "RTX 4090 24GB (ExLlamaV2 EXL2)",
                         *           "prefillSpeedTokPerSec": 3800,
                         *           "decodeSpeedTokPerSec": 105,
                         *           "vramBandwidth": "1.01 TB/s (GDDR6X)",
                         *           "badge": "Localmaxxing #1 Consumer"
                         *         },
                         *         {
                         *           "id": "dual_rtx3090",
                         *           "name": "Dual RTX 3090 48GB (TP2 ExLlamaV2 70B)",
                         *           "prefillSpeedTokPerSec": 4600,
                         *           "decodeSpeedTokPerSec": 78,
                         *           "vramBandwidth": "1.87 TB/s Combined",
                         *           "badge": "Localmaxxing 70B Rig"
                         *         },
                         *         {
                         *           "id": "rtx3090_llamacpp",
                         *           "name": "RTX 3090 24GB (llama.cpp Q4_K_M)",
                         *           "prefillSpeedTokPerSec": 2400,
                         *           "decodeSpeedTokPerSec": 65,
                         *           "vramBandwidth": "936 GB/s (GDDR6X)",
                         *           "badge": "Localmaxxing Budget King"
                         *         }
                         *       ],
                         *       "scenarios": [
                         *         {
                         *           "id": "chat",
                         *           "label": "Standard chat",
                         *           "promptTokens": 2048,
                         *           "outputTokens": 512
                         *         },
                         *         {
                         *           "id": "rag",
                         *           "label": "RAG query",
                         *           "promptTokens": 4096,
                         *           "outputTokens": 512
                         *         }
                         *       ],
                         *       "schema_version": "1"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/localmaxxing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raw community benchmark runs (flattened, model-normalized)
         * @description Bare call returns a hardware-group summary. With any filter, returns a cursor-paginated run list: { total, items[], has_more, next_cursor } sorted by decode speed desc (runId tiebreak) — follow next_cursor until has_more is false.
         */
        get: {
            parameters: {
                query?: {
                    /** @description substring match on rig name/key */
                    hardware?: string;
                    /** @description substring match on normalized family or hfId */
                    model?: string;
                    /** @description exact quantization, e.g. q4_k_m */
                    quant?: string;
                    /** @description only runs measured at this context length (<1000, 1000–7999, 8000–31999, ≥32000 tokens) */
                    context_band?: "lt1k" | "1k-8k" | "8k-32k" | "32k+";
                    /** @description page size */
                    limit?: number;
                    /** @description opaque next_cursor from the previous page (keyset resumption; stable across upstream inserts) */
                    cursor?: string;
                    /** @description Serve the pinned dataset snapshot instead of live data. IDs from /api/snapshots; unknown IDs fall back to current data with snapshot.served=false. */
                    snapshot?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hardware summary, or paginated run list { total, items[], has_more, next_cursor }; both carry a machine-readable `caveats` array (single-stream-only, self-reported data, engine mix) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "description": "Raw comparable runs (modelFamily collapses repo/quant variants of the same base model). Cursor pagination: follow next_cursor until has_more is false.",
                         *       "snapshot": {
                         *         "id": "snapshot-2026-08-21-a1b2c3d4",
                         *         "createdAt": "2026-08-21T09:14:03.000Z",
                         *         "runCount": 3642
                         *       },
                         *       "snapshotAt": "2026-08-21T09:14:03.512Z",
                         *       "schema_version": "1",
                         *       "total": 214,
                         *       "caveats": [
                         *         {
                         *           "code": "single_stream_only",
                         *           "severity": "medium",
                         *           "summary": "Dataset only contains batchSize=1 runs — not batched-serving throughput.",
                         *           "detail": "All 3642 runs report concurrency ≤ 1."
                         *         },
                         *         {
                         *           "code": "self_reported_unvalidated",
                         *           "severity": "medium",
                         *           "summary": "Community-submitted runs, not independently verified; trust medians over single runs.",
                         *           "detail": "Submissions are sanity-bounded and deduplicated but not lab-measured."
                         *         }
                         *       ],
                         *       "items": [
                         *         {
                         *           "runId": 58213,
                         *           "createdAt": "2026-07-30T18:22:41.000Z",
                         *           "modelFamily": "qwen3.6-27b",
                         *           "modelName": "unsloth/Qwen3.6-27B-MTP-GGUF",
                         *           "hardwareKey": "rtx4090",
                         *           "hardware": "RTX 4090 24GB",
                         *           "hwClass": "discrete_gpu",
                         *           "gpu": "RTX 4090",
                         *           "gpuCount": 1,
                         *           "engine": "llama.cpp",
                         *           "engineVersion": "b6123",
                         *           "quantization": "q4_k_m",
                         *           "prefillTokPerSec": 3820,
                         *           "decodeTokPerSec": 108,
                         *           "contextLength": 8192,
                         *           "contextBand": "8k-32k",
                         *           "ageDays": 23,
                         *           "staleness": "recent",
                         *           "source": "https://localmaxxing.com/en/runs/58213"
                         *         }
                         *       ],
                         *       "has_more": true,
                         *       "next_cursor": "MTA4fCI1ODIxMyI"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Watch feeds: list registered hardware+model combos (#109)
         * @description Public listing of watched combos — never includes secrets or webhook URLs. POST to create a watch; DELETE ?id=&secret= to remove one.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Feature description + registered watches (watchId, label, hasWebhook, createdAt) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "description": "Watch feeds (#109): subscribe to a hardware+model combination…",
                         *       "maxWatches": 500,
                         *       "totalWatches": 1,
                         *       "watches": [
                         *         {
                         *           "watchId": "watch_abc123_x9",
                         *           "label": "RTX 4090 + Qwen3 32B",
                         *           "model": "Qwen3 32B",
                         *           "hardware": "RTX 4090",
                         *           "quant": null,
                         *           "hasWebhook": false,
                         *           "createdAt": "2026-08-22T10:00:00.000Z"
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        /**
         * Create a watch for a hardware+model combo (#109)
         * @description Body: { model?, hardware?, quant?, webhookUrl? } — at least one of model/hardware required; webhookUrl must be https. Returns 201 with watchId + secret (shown exactly once; required to DELETE, sent to your webhook as X-Watch-Secret) and a ready-made rssUrl. RSS polling needs no webhook: GET /api/watch/rss.xml?model=&hardware=&quant=.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    /**
                     * @example {
                     *       "model": "Qwen3 32B",
                     *       "hardware": "RTX 4090",
                     *       "quant": "q4_k_m",
                     *       "webhookUrl": "https://example.com/hooks/llm-watch"
                     *     }
                     */
                    "application/json": unknown;
                };
            };
            responses: {
                /** @description Watch created (watchId, secret, rssUrl, matchingExistingRuns preview) */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Invalid body (code validation_failed with per-field errors) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
                /** @description Watch store unavailable (code watch_store_unavailable) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        /** Remove a watch */
        delete: {
            parameters: {
                query: {
                    /** @description watchId from the POST response */
                    id: string;
                    /** @description one-time secret from the POST response (also accepted as X-Watch-Secret header) */
                    secret: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Watch removed */
                204: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Wrong or missing secret (code invalid_secret) */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Unknown watchId (code watch_not_found) */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch/rss.xml": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * RSS 2.0 feed of community runs for a watched combo (#109)
         * @description Filters mirror GET /api/localmaxxing (model/hardware substring, quant exact). Items are the newest matching runs (max 50), each linking to the upstream run. Poll like any feed — no registration needed.
         */
        get: {
            parameters: {
                query?: {
                    /** @description substring match on normalized family / hfId / display name */
                    model?: string;
                    /** @description substring match on rig name/key */
                    hardware?: string;
                    /** @description exact quantization */
                    quant?: string;
                    /** @description only runs measured in the last N days (undated runs always included) */
                    days?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description RSS 2.0 XML (application/rss+xml); X-Matched-Runs header reports the pre-cap match count */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/watch/dispatch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Deliver unseen matching runs to registered webhooks (#109)
         * @description Cron-friendly (Vercel Cron sends GET). For each watch with a webhookUrl: POST a watch.new_runs payload (X-Watch-Secret header) with runs created after the watch that are not yet in its bounded seen-set, then persist the set. Set WATCH_DISPATCH_SECRET to require ?secret= / x-dispatch-secret. Delivery failures are reported per watch, never thrown.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description { dispatched, totalNewRuns, results[], previewPayload } */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description WATCH_DISPATCH_SECRET set and not provided (code unauthorized) */
                401: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                429: components["responses"]["RateLimited"];
                /** @description Watch store unavailable (code watch_store_unavailable) */
                503: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated speeds: median + IQR + 95% bootstrap CI per group
         * @description Outlier-resistant stats per hardware×model-family group (default). Each median carries a 95% percentile bootstrap confidence interval (2,000 resamples) in ci95 {lo, hi}, plus a "median [lo–hi]" label string. Regroup with ?groupBy=hardware|model|quant. Cursor-paginated: { total, items[], has_more, next_cursor } sorted by median decode desc (group key tiebreak). Each group carries confidence {runs, iqrSpreadPct, outliers, newestRunAgeDays, grade} and cross_check {relatedRigComparisons, contradictions[]} comparing multi-GPU rigs against the single-GPU baseline on the same model/quant.
         */
        get: {
            parameters: {
                query?: {
                    groupBy?: "hardwareModel" | "hardware" | "model" | "quant";
                    hardware?: string;
                    model?: string;
                    quant?: string;
                    hwClass?: "discrete_gpu" | "unified" | "cpu_only";
                    /** @description only runs measured at this context length; groups mixing bands carry mixedContextBands + a warning */
                    context_band?: "lt1k" | "1k-8k" | "8k-32k" | "32k+";
                    /** @description page size */
                    limit?: number;
                    /** @description opaque next_cursor from the previous page (keyset resumption; stable across upstream inserts) */
                    cursor?: string;
                    /** @description Serve the pinned dataset snapshot instead of live data. IDs from /api/snapshots; unknown IDs fall back to current data with snapshot.served=false. */
                    snapshot?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Paginated groups { total, items[], has_more, next_cursor }; items carry median/q1/q3/min/max prefill & decode with 95% bootstrap CIs on each median, bestRun, a confidence block and crossCheck. Top-level and per-group `caveats` arrays flag n=1 groups and mixed engine versions. */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "description": "Aggregated community benchmark speeds (median + IQR + 95% bootstrap CI per group).",
                         *       "snapshot": {
                         *         "id": "snapshot-2026-08-21-a1b2c3d4",
                         *         "createdAt": "2026-08-21T09:14:03.000Z",
                         *         "runCount": 3642
                         *       },
                         *       "snapshotAt": "2026-08-21T09:14:03.512Z",
                         *       "schema_version": "1",
                         *       "total": 187,
                         *       "caveats": [
                         *         {
                         *           "code": "n1_groups",
                         *           "severity": "medium",
                         *           "summary": "22% of groups rest on a single run — treat as anecdotal.",
                         *           "detail": "18 of 82 returned groups have runs=1.",
                         *           "pct": 22,
                         *           "groupsWithOneRun": 18,
                         *           "totalGroups": 82
                         *         }
                         *       ],
                         *       "items": [
                         *         {
                         *           "key": "rtx4090|qwen3.6-27b",
                         *           "runs": 14,
                         *           "prefill": {
                         *             "q1": 3601,
                         *             "median": 3800,
                         *             "q3": 3950,
                         *             "min": 3210,
                         *             "max": 4102,
                         *             "ci95": {
                         *               "lo": 3701,
                         *               "hi": 3902
                         *             },
                         *             "label": "3800 [3701–3902]"
                         *           },
                         *           "decode": {
                         *             "q1": 99,
                         *             "median": 105,
                         *             "q3": 112,
                         *             "min": 88,
                         *             "max": 118,
                         *             "ci95": {
                         *               "lo": 101,
                         *               "hi": 110
                         *             },
                         *             "label": "105 [101–110]"
                         *           },
                         *           "modelFamilies": [
                         *             "qwen3.6-27b"
                         *           ],
                         *           "engines": [
                         *             "llama.cpp"
                         *           ],
                         *           "mixedEngines": false,
                         *           "caveats": [],
                         *           "confidence": {
                         *             "runs": 14,
                         *             "iqrSpreadPct": 12.38,
                         *             "outliers": 0,
                         *             "newestRunAgeDays": 3,
                         *             "grade": "high"
                         *           },
                         *           "crossCheck": {
                         *             "relatedRigComparisons": [],
                         *             "contradictions": []
                         *           },
                         *           "bestRun": {
                         *             "runId": 58213,
                         *             "modelName": "unsloth/Qwen3.6-27B-MTP-GGUF",
                         *             "hardware": "RTX 4090 24GB",
                         *             "engine": "llama.cpp",
                         *             "engineVersion": "b6123",
                         *             "quantization": "q4_k_m",
                         *             "prefillTokPerSec": 3820,
                         *             "decodeTokPerSec": 108,
                         *             "createdAt": "2026-07-30T18:22:41.000Z",
                         *             "source": "https://localmaxxing.com/en/runs/58213"
                         *           }
                         *         }
                         *       ],
                         *       "has_more": true,
                         *       "next_cursor": "MTA1fCJydDQwOTB8cXdlbjMuNi0yN2Ii"
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ranked answers: fastest or cheapest rigs for given constraints
         * @description Example: /api/best?by=decode&maxParamsB=8&quant=q4_k_m → top rigs for ≤8B models at Q4_K_M by median decode speed. by=cost ranks by cost-efficiency instead. Medians carry 95% bootstrap CIs (medianXxxCi95 / medianXxxLabel). Responses carry a deterministic `id` (hash of the resolved filters) replayable via /api/calc/{id}?endpoint=best&<same filters>.
         */
        get: {
            parameters: {
                query?: {
                    by?: "decode" | "prefill" | "cost";
                    /** @description cost mode: rig purchase price in USD (default 0) */
                    price?: number;
                    /** @description cost mode: $/kWh (default 0.15) */
                    electricityRate?: number;
                    /** @description cost mode: whole-rig watts; defaults to an estimate per hwClass */
                    powerWatts?: number;
                    /** @description cost mode: spread price over this many months (default 36) */
                    amortizationMonths?: number;
                    /** @description cost mode: scenario shape (default 2048) */
                    promptTokens?: number;
                    /** @description cost mode: scenario shape (default 512) */
                    outputTokens?: number;
                    model?: string;
                    /** @description only models at or under this size */
                    maxParamsB?: number;
                    quant?: string;
                    hwClass?: "discrete_gpu" | "unified" | "cpu_only";
                    hardware?: string;
                    /** @description only runs measured at this context length (<1000, 1000–7999, 8000–31999, ≥32000 tokens) */
                    context_band?: "lt1k" | "1k-8k" | "8k-32k" | "32k+";
                    /** @description exclude rigs whose memory cannot hold the model at the given context (estimated) */
                    fitCheck?: boolean;
                    /** @description context for fitCheck; providing it implies fitCheck=true */
                    contextLength?: number;
                    /** @description KV cache dtype bytes for fitCheck (2 = fp16) */
                    precisionBytes?: number;
                    /** @description batch size for fitCheck KV cache math */
                    batchSize?: number;
                    limit?: number;
                    /** @description Serve the pinned dataset snapshot instead of live data. IDs from /api/snapshots; unknown IDs fall back to current data with snapshot.served=false. */
                    snapshot?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ranked groups with medians, per-row `caveats` (n=1, mixed engines), a confidence block and a top-level `caveats` array, plus source links; with fitCheck, each result carries an estimated vramFit breakdown and the response reports excludedRuns. Each result includes a `pricing` object: USD street-price estimate with low/high range, perGpu breakdown for multi-GPU rigs, asOf date, and eBay (new + used) and Craigslist search links to verify against live listings. `pricing` is null when no anchor exists (cpu_only, unknown GPUs). Each result also carries `explain`: a one-sentence human-readable explanation combining the VRAM-fit math (weights + KV estimates) with the measured source, e.g. '24GB fits 8B q4_k_m weights ~5GB + 32k KV ~4GB with 14GB headroom; measured 100 tok/s decode from run #a1' — pass-through ready for agent chat pipelines. Each result also includes a `power` object (#69): board power (TDP, per card and total), typical whole-rig wattage under sustained inference, and a recommended PSU size with transient-headroom notes — so a dual-GPU recommendation can be sanity-checked against the user's actual electrical setup. `power` is null when no anchor exists (cpu_only, unknown GPUs). */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        /**
                         * @example {
                         *       "id": "calc_7f2c91b04da3",
                         *       "description": "Ranked hardware×model groups by measured community speed. Medians are outlier-resistant.",
                         *       "rankedBy": "decode",
                         *       "snapshot": {
                         *         "id": "snapshot-2026-08-21-a1b2c3d4",
                         *         "createdAt": "2026-08-21T09:14:03.000Z",
                         *         "runCount": 3642
                         *       },
                         *       "snapshotAt": "2026-08-21T09:14:03.512Z",
                         *       "matchedRuns": 214,
                         *       "schema_version": "1",
                         *       "caveats": [
                         *         {
                         *           "code": "single_stream_only",
                         *           "severity": "medium",
                         *           "summary": "Dataset only contains batchSize=1 runs — not batched-serving throughput.",
                         *           "detail": "All 3642 runs report concurrency ≤ 1."
                         *         }
                         *       ],
                         *       "warnings": [],
                         *       "results": [
                         *         {
                         *           "hardware": "RTX 4090 24GB",
                         *           "hardwareKey": "rtx4090",
                         *           "hwClass": "discrete_gpu",
                         *           "gpu": "RTX 4090",
                         *           "gpuCount": 1,
                         *           "vramGb": 24,
                         *           "modelFamily": "qwen3.6-27b",
                         *           "exampleModel": "unsloth/Qwen3.6-27B-MTP-GGUF",
                         *           "quantization": "q4_k_m",
                         *           "engine": "llama.cpp",
                         *           "runsInGroup": 14,
                         *           "confidence": {
                         *             "runs": 14,
                         *             "iqrSpreadPct": 12.38,
                         *             "outliers": 0,
                         *             "newestRunAgeDays": 3,
                         *             "grade": "high"
                         *           },
                         *           "medianPrefillTokPerSec": 3800,
                         *           "medianDecodeTokPerSec": 105,
                         *           "bestDecodeTokPerSec": 118,
                         *           "medianPrefillCi95": {
                         *             "lo": 3701,
                         *             "hi": 3902
                         *           },
                         *           "medianPrefillLabel": "3800 [3701–3902]",
                         *           "medianDecodeCi95": {
                         *             "lo": 101,
                         *             "hi": 110
                         *           },
                         *           "medianDecodeLabel": "105 [101–110]",
                         *           "caveats": [],
                         *           "effectiveVramGb": 24,
                         *           "pricing": {
                         *             "estimateUsd": 1650,
                         *             "lowUsd": 1400,
                         *             "highUsd": 1900,
                         *             "perGpu": [
                         *               {
                         *                 "gpu": "RTX 4090",
                         *                 "estimateUsd": 1650
                         *               }
                         *             ],
                         *             "asOf": "2026-08-01",
                         *             "links": {
                         *               "ebay": "https://www.ebay.com/sch/i.html?_nkw=rtx+4090",
                         *               "ebayUsed": "https://www.ebay.com/sch/i.html?_nkw=rtx+4090&LH_ItemCondition=3000",
                         *               "craigslist": "https://craigslist.org/search/sss?query=rtx+4090"
                         *             }
                         *           },
                         *           "explain": "24GB VRAM fits qwen3.6-27b q4_k_m weights ~16GB + 32k KV ~7GB with ~1GB headroom; measured 105 tok/s decode median across 14 community runs."
                         *         }
                         *       ]
                         *     }
                         */
                        "application/json": unknown;
                    };
                };
                429: components["responses"]["RateLimited"];
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Service health and upstream data freshness
         * @description Liveness probe. Returns ok plus upstreamFreshness (fresh/stale/empty, last sync time, cached row count) and cacheAge in seconds. Human status page at /status.html.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description {ok, service, time, upstreamFreshness, cacheAge} */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Health handler itself failed */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sizing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Hardware sizing recommendation for a workload spec (VRAM fit + expected TTFT/TPOT)
         * @description One canonical query for deployment planning: pass a workload spec, get ranked rigs with required-VRAM math (weights + KV cache at target context × concurrency + overhead) and expected TTFT/TPOT from aggregated benchmark medians, plus per-group sample confidence.
         */
        get: {
            parameters: {
                query: {
                    /** @description model family / hfId substring, e.g. qwen */
                    model: string;
                    /** @description target context per request (drives KV-cache VRAM) */
                    contextLength?: number;
                    /** @description simultaneous requests; scales KV cache, decays per-user decode ~B^-0.25 */
                    concurrency?: number;
                    /** @description tokens prefilled per request (TTFT input) */
                    promptTokens?: number;
                    /** @description tokens decoded per request */
                    outputTokens?: number;
                    /** @description SLO cap on expected TTFT */
                    maxTtftSeconds?: number;
                    /** @description SLO cap on expected TPOT */
                    maxTpotMs?: number;
                    /** @description budget cap: rig memory (VRAM or unified) must fit under this */
                    maxVramGb?: number;
                    /** @description explicit KV arch (with kvHeads+headDim skips the per-param-count estimate) */
                    numLayers?: number;
                    kvHeads?: number;
                    headDim?: number;
                    /** @description exact quantization match */
                    quant?: string;
                    hwClass?: "discrete_gpu" | "unified" | "cpu_only";
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description workload echo, assumptions, and ranked recommendations with vramFit, expected, confidence, meetsSlo, and a one-sentence human-readable `explain` string combining fit math with the measured source (#73) */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/parse-constraints": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Parse plain-language constraints into the canonical constraint JSON
         * @description Converts a natural-language constraint string (e.g. "self-hosted Qwen 27B at Q4 for 10 users under $1500") into the canonical constraint struct used by /api/sizing and /api/best. Deterministic regex/heuristics — no external LLM calls. Returns the echoed input, the parsed struct (null = not stated) and an `ambiguities` array listing every assumption (e.g. "10 users: assume 1 stream each or batched?"), plus a ready-made `sizingQuery` for the downstream decision endpoint.
         */
        get: {
            parameters: {
                query: {
                    /** @description Plain-language constraints, e.g. self-hosted Qwen 27B at Q4 for 10 users under $1500 */
                    q: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description {input, recognizedCount, constraints{deployment,modelFamily,paramsB,quantization,contextLength,concurrency,budgetUsdMax,minDecodeTokPerSec,maxVramGb,hwClass}, ambiguities[], sizingQuery} */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            input?: string;
                            recognizedCount?: number;
                            constraints?: {
                                /** @enum {string|null} */
                                deployment?: "self-hosted" | "cloud" | null;
                                modelFamily?: string | null;
                                paramsB?: number | null;
                                quantization?: string | null;
                                contextLength?: number | null;
                                concurrency?: number | null;
                                budgetUsdMax?: number | null;
                                minDecodeTokPerSec?: number | null;
                                maxVramGb?: number | null;
                                /** @enum {string|null} */
                                hwClass?: "discrete_gpu" | "unified" | "cpu_only" | null;
                            };
                            ambiguities?: {
                                field?: string;
                                message?: string;
                            }[];
                            /** @description Ready-made /api/sizing query string; null when nothing mappable was recognized */
                            sizingQuery?: string | null;
                        };
                    };
                };
                /** @description Missing q parameter (code INVALID_PARAMS) */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
                /** @description Rate limited (code RATE_LIMITED) */
                429: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/problem+json": components["schemas"]["Problem"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/snapshots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Versioned dataset snapshot IDs
         * @description Lists content-addressed dataset snapshots (e.g. snapshot-2026-08-21-a1b2c3d4). Pass any listed ID as ?snapshot= on /api/localmaxxing, /api/benchmarks or /api/best to get reproducible numbers. Snapshot IDs are stable for identical run sets within a fetch-time bucket; instances keep a bounded in-memory ring, so old IDs may expire.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description {current, snapshots[]} */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 problem+json error body. Content-Type: application/problem+json. */
        Problem: {
            /**
             * Format: uri
             * @description Stable problem-type URI, e.g. .../problems/invalid-params
             */
            type: string;
            /** @description Short human-readable summary */
            title: string;
            /** @description HTTP status code */
            status: number;
            /** @description Human-readable explanation of this occurrence */
            detail?: string;
            /** @description Request path + query that produced the error */
            instance?: string;
            /**
             * @description Stable machine-readable error code — branch on this, not on title/detail prose
             * @enum {string}
             */
            code: "INVALID_PARAMS" | "NOT_FOUND" | "RATE_LIMITED" | "UPSTREAM_UNAVAILABLE" | "INTERNAL";
        };
    };
    responses: {
        /** @description Rate limit exhausted for this window. Back off for Retry-After seconds, then resume. */
        RateLimited: {
            headers: {
                /** @description Max requests per 60s window per client (best-effort, per serverless instance). */
                "X-RateLimit-Limit"?: number;
                /** @description Requests left in the current window. */
                "X-RateLimit-Remaining"?: number;
                /** @description Unix epoch seconds when the current window resets. */
                "X-RateLimit-Reset"?: number;
                /** @description Seconds until the window resets and requests are accepted again. */
                "Retry-After"?: number;
                [name: string]: unknown;
            };
            content: {
                "application/json": {
                    error?: string;
                    limit?: number;
                    remaining?: number;
                    /** @description Unix epoch seconds */
                    reset?: number;
                    retryAfterSeconds?: number;
                };
            };
        };
    };
    parameters: never;
    requestBodies: never;
    headers: {
        /** @description Max requests per 60s window per client (best-effort, per serverless instance). */
        "X-RateLimit-Limit": number;
        /** @description Requests left in the current window. */
        "X-RateLimit-Remaining": number;
        /** @description Unix epoch seconds when the current window resets. */
        "X-RateLimit-Reset": number;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
