/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/compute": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Run inference math (TTFT, TPOT, walltime, VRAM)
         * @description Pass ?model=<name> plus parameters. Omit model for a self-describing capability list. Also accepts POST with a JSON body.
         */
        get: {
            parameters: {
                query?: {
                    model?: "singleTurn" | "speculative" | "batched" | "agentic" | "kvCache";
                    /** @description singleTurn/batched/agentic */
                    promptTokens?: number;
                    /** @description singleTurn/batched/agentic */
                    outputTokens?: number;
                    /** @description tok/s */
                    prefillSpeed?: number;
                    /** @description tok/s */
                    decodeSpeed?: number;
                    /** @description agentic */
                    numTurns?: number;
                    /** @description agentic */
                    enablePrefixCaching?: boolean;
                    /** @description batched/kvCache */
                    batchSize?: number;
                    /** @description speculative: draft tokens per step */
                    draftTokens?: number;
                    /** @description speculative: 0..1 */
                    acceptanceRate?: number;
                    /** @description kvCache preset arch */
                    architecture?: "llama70b" | "llama8b" | "qwen72b" | "mistral7b";
                    /** @description kvCache */
                    contextLength?: number;
                    /** @description kvCache: FP16/FP8/INT4 */
                    precisionBytes?: 2 | 1 | 0.5;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Computed metrics object */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/presets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Built-in hardware speed presets and workload scenarios */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description {hardware[], scenarios[]} */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/localmaxxing": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Raw community benchmark runs (flattened, model-normalized)
         * @description Bare call returns a hardware-group summary. Filters: ?hardware=<substr>&model=<substr>&quant=<exact>&limit=N. Runs carry measured prefillTokPerSec / decodeTokPerSec.
         */
        get: {
            parameters: {
                query?: {
                    /** @description substring match on rig name/key */
                    hardware?: string;
                    /** @description substring match on normalized family or hfId */
                    model?: string;
                    /** @description exact quantization, e.g. q4_k_m */
                    quant?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Hardware summary or run list */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/benchmarks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Aggregated speeds: median + IQR per group
         * @description Outlier-resistant stats per hardware×model-family group (default). Regroup with ?groupBy=hardware|model|quant.
         */
        get: {
            parameters: {
                query?: {
                    groupBy?: "hardwareModel" | "hardware" | "model" | "quant";
                    hardware?: string;
                    model?: string;
                    quant?: string;
                    hwClass?: "discrete_gpu" | "unified" | "cpu_only";
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Groups with median/q1/q3/min/max prefill & decode, plus bestRun */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/best": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ranked answers: fastest rigs for given constraints
         * @description Example: /api/best?by=decode&maxParamsB=8&quant=q4_k_m → top rigs for ≤8B models at Q4_K_M by median decode speed.
         */
        get: {
            parameters: {
                query?: {
                    by?: "decode" | "prefill";
                    model?: string;
                    /** @description only models at or under this size */
                    maxParamsB?: number;
                    quant?: string;
                    hwClass?: "discrete_gpu" | "unified" | "cpu_only";
                    hardware?: string;
                    limit?: number;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description Ranked groups with medians and source links */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: never;
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
